- name : Configure Docker on EC2 Instances
  hosts : webservers
  become: true
  connection : ssh
  tasks :

  - name: Deploy kuber pod 
    command:  kubectl create deployment insureme --image=docker.io/ankeetchauhan/healthcare --port=8081
    
