- name: Configure Docker on EC2 Instances
  hosts: webservers
  become: true
  connection: ssh
  tasks :

  - name: Deploy kuber pod 
    command:  kubectl create deployment health3 --image=docker.io/ankeetchauhan/health2 --port=8081
    
